main: de.safespacegerman.dependencies.SpaceDependencies
name: SpaceDependencies
version: ${project.version}
api-version: 1.19

website: https://whackdevelopment.com

authors:
  - 'whackdevelopment.com'

load: STARTUP
